version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  test:
    jobs:
      - test-linux:
          name: Python 3.5
          docker-image: circleci/python:3.5-jessie
      - test-linux:
          name: Python 3.6
          docker-image: circleci/python:3.6-jessie
      - test-linux:
          name: Python 3.7
          docker-image: circleci/python:3.7-stretch
      - test-linux:
          name: Python 3.8
          docker-image: circleci/python:3.8-buster
      - test-linux:
          name: Python 3.9
          docker-image: circleci/python:3.9-rc-buster
      - test-windows:
          name: Windows Python 3
          py3: true

jobs:
  test-linux:
    parameters:
      docker-image:
        type: string
      test-packaging:
        type: boolean
        default: true
      test-with-codeclimate:
        type: boolean
        default: false
      test-with-mypy:
        type: boolean
        default: true
    docker:
      - image: <<parameters.docker-image>>
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            sudo pip install --upgrade pip;
            sudo pip install 'virtualenv~=16.0';
            sudo pip install -r test-requirements.txt;
            sudo pip install -r test-filesource-optional-requirements.txt;
            sudo pip install -r consul-requirements.txt;
            sudo python setup.py install;
            pip freeze
      - when:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests (with CodeClimate)
                command: |
                  mkdir test-reports
                  pytest -s --cov=ldclient --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
                  sh -c '[ -n "${CODECLIMATE_REPO_TOKEN+1}" ] && codeclimate-test-reporter || echo "No CODECLIMATE_REPO_TOKEN value is set; not publishing coverage report"'
      - unless:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests
                command: |
                  mkdir test-reports
                  pytest -s --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
      - when:
          condition: <<parameters.test-packaging>>
          steps:
            - run:
                name: test packaging/install
                command: |
                  sudo rm -rf dist *.egg-info
                  ./test-packaging/test-packaging.sh
      - when:
          condition: <<parameters.test-with-mypy>>
          steps:
            - run:
                name: verify typehints
                command: |
                  export PATH="/home/circleci/.local/bin:$PATH"
                  mypy --config-file mypy.ini ldclient testing
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    parameters:
      py3:
        type: boolean
    steps:
      - checkout
      - run:
          name: install Python 3
          command: choco install python --no-progress
      - run:
          name: set up DynamoDB
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf dynamo.zip https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip
            mkdir dynamo
            Expand-Archive -Path dynamo.zip -DestinationPath dynamo
            cd dynamo
            javaw -D"java.library.path=./DynamoDBLocal_lib" -jar DynamoDBLocal.jar
          background: true
      - run:
          name: set up Consul
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf consul.zip https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_windows_amd64.zip
            mkdir consul
            Expand-Archive -Path consul.zip -DestinationPath consul
            cd consul
            sc.exe create "Consul" binPath="$(Get-Location)/consul.exe agent -dev"
            sc.exe start "Consul"
      - run:
          name: start Redis
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf redis.zip https://github.com/MicrosoftArchive/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.zip
            mkdir redis
            Expand-Archive -Path redis.zip -DestinationPath redis
            cd redis
            ./redis-server --service-install
            ./redis-server --service-start
            Start-Sleep -s 5
            ./redis-cli ping
      - run:
          name: install requirements
          command: |
            python --version
            pip install -r test-requirements.txt
            pip install -r consul-requirements.txt
            python setup.py install
      - run:
          name: run tests
          command: |
            mkdir test-reports
            python -m pytest -s --junitxml=test-reports/junit.xml testing;
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
